### ISSUE TITLE
Добавить обработку android-устройств

### ISSUE THREAD

**Issue by MikerStudio** [Rt-Fox/look.city-frontend#3]
Когда с ведра заходишь высота окна больше высоты экрана

**Comment by Henk0** [comment]
А я то как это сделаю
шо

**Comment by MikerStudio** [comment]
`
    if ('android' in navigator.userAgent.toLowerCase()) {
        document.write('<meta name="viewport" content="width=device-width, height=' + window.innerHeight + ', initial-scale=1.0">');
     }`
